//AUTOGENERATED FILE! CHANGES WILL BE OVERWRITTEN
import java.io._
object measureTADL2Burst{
	def main(args: Array[String]): Unit = {
		generateTrace()
		measureMultiple(20, "results/TADL2Burst.txt")
	}

	var eventCount: Int = 250000
	var tesslaMonitorInstance : TesslaMonitor = null
	protected var outputFinal: Boolean = false
	protected var outputValue: Boolean = false

	var burstLength: Int = 2000
	var maxOccurrences : Int = 50
	var traceSet : BurstConstraintGenerator = null

	def measureConstraint() : (Long, Long, Long) = {
		var min = Long.MaxValue
		var max = Long.MinValue
		var avg = 0L
		var eventCounter = 0
		tesslaMonitorInstance = new TesslaMonitor()
		tesslaMonitorInstance.out_final = outputFuncFinal
		tesslaMonitorInstance.out_value = outputFuncValue
		var currentEvents: Array[Event] = traceSet.getNextTimestampsEvents();
		var ctr = 0
		while (currentEvents.length != 0 && !(outputFinal && ! outputValue)) {
			for (i <- 0 to currentEvents.length-1){
				if (currentEvents(i).getOwnerStream().getName().equals("event"))
					tesslaMonitorInstance.set_var_event(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())
			}
		eventCounter = eventCounter+1
			var time1= System.nanoTime()
			tesslaMonitorInstance.flush();
			var time2= System.nanoTime
			if (outputFinal && ! outputValue){
				min = -1L
				max = -1L
				avg = 0L
				println("Error state reached MeasureConstraint()")
			}
			var timeEvent = time2-time1
			min = if (timeEvent < min) timeEvent else min
			max = if (timeEvent > max) timeEvent else max
			avg += timeEvent
			currentEvents = traceSet.getNextTimestampsEvents();
			ctr = ctr+1
		}
		traceSet.resetOutputCounter()
		if (eventCounter == 0)
			(0L, 0L, 0L)
		else
			(min, max, avg / eventCounter)
	}

	def measureMultiple(count: Int, resultFilePath: String) : Unit = {
		var results: Array[(Long, Long, Long)] = new Array[(Long, Long, Long)](count)
		for (i <- 0 to count-1){
			println("Measure " + (i+1) + " of " + count)
			var result = measureConstraint()
			results(i) = result
		}
		if (!storeResultsToFile(results, resultFilePath))
			println("Cannot write results to " + resultFilePath);
	}

	def storeResultsToFile(measures: Array[(Long, Long, Long)], filePath: String) : Boolean = {
		try{
			var fileWriter = new FileWriter(filePath)
			fileWriter.write("(min, max, average) of the run times per event in the individual runs.\n")
			var averageVals = average(measures)
			fileWriter.write("overallAverage: (" + averageVals._1 + ", " + averageVals._2 + ", " + averageVals._3 + ")\n")
			for (i <- 0 to measures.length-1) {
				fileWriter.write("measure " + (i+1) + " of " + (measures.length) + ": (" + measures(i)._1 + ", " + measures(i)._2 + ", " + measures(i)._3+ ")\n")
			}
			fileWriter.close()
		} catch {
			case e: IOException => return false
		}
		return true
	}

	def average(measures: Array[(Long, Long, Long)]): (Long, Long, Long) = {
		var results = (0L, 0L, 0L)
		for (i <- 0 to measures.length-1){
			results = (results._1 + measures(i)._1,
						results._2 + measures(i)._2,
						results._3 + measures(i)._3)
		}
		return (results._1 / measures.length,
					results._2 / measures.length,
					results._3 / measures.length)
	}

	def outputFuncValue(value: Boolean, timestamp: Long, name: String, error: Throwable) : Unit = {
		if (error != null){
			println("An Error occurred at timestamp " + timestamp + ": " + error.getMessage());
		} else {
			outputValue = value
			if (outputFinal && ! outputValue)
				println("Error! Invalid Output!");
		}
	}

	def outputFuncFinal(value: Boolean, timestamp: Long, name: String, error: Throwable) : Unit = {
		if (error != null){
			println("An Error occurred at timestamp " + timestamp + ": " + error.getMessage());
		} else {
			outputFinal = value
			if (outputFinal && ! outputValue)
				println("Error! Invalid Output!");
		}
	}

	def generateTrace(): Boolean = {
		tesslaMonitorInstance = new TesslaMonitor()
		traceSet = new BurstConstraintGenerator()
		var res: Boolean = traceSet.generateTestTrace(eventCount, burstLength, maxOccurrences)
		if (res) {
			traceSet.initOutput();
		}
		res
	}

}
