import java.io.FileWriter
import java.io.IOException

class TimeMeasureScalaClassCreatorTADLSporadic extends TimeMeasureScalaClassCreator{

	def generateEntireObject(scalaFilePath: String, scalaObjectName: String, resultFilePath: String, repetitionCount: Int, eventCount: Int,
			lower: Int, upper: Int, jitter: Int, minimum: Int, printInputEvents: Boolean): Boolean= {
		var constraintCreator = new TimeMeasureScalaClassCreatorTADLSporadic
		try {
			var fileWriter = new FileWriter(scalaFilePath)
			fileWriter.write("//AUTOGENERATED FILE! CHANGES WILL BE OVERWRITTEN\n")
			fileWriter.write("import java.io._\n")
			fileWriter.write("object " + scalaObjectName + "{\n")
			constraintCreator.generateMainMethod(fileWriter, 1, repetitionCount, resultFilePath)
			constraintCreator.generateMemberVariableListGeneral(fileWriter, 1, eventCount)
			constraintCreator.generateMemberVariableListExtended(fileWriter, 1, lower, upper, jitter, minimum)
			constraintCreator.generateMeasureConstraint(fileWriter, 1, printInputEvents)
			constraintCreator.generateMeasureMultiple(fileWriter, 1)
			constraintCreator.generateStoreResultsToFile(fileWriter, 1)
			constraintCreator.generateAverage(fileWriter, 1)
			constraintCreator.generateOutputFuncValue(fileWriter, 1, printInputEvents)
			constraintCreator.generateOutputFuncFinal(fileWriter, 1, printInputEvents)
			constraintCreator.generateGenerateTrace(fileWriter, 1, repetitionCount, resultFilePath)
			fileWriter.write("}\n")
			fileWriter.flush()
			fileWriter.close()
		} catch {
			case e: IOException => return false
		}
		return true
	}

	protected def generateMemberVariableListExtended(writer: FileWriter, prevTabCount: Int, lower: Int, upper: Int,
			jitter: Int, mimimum: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "var lower: Int = " + lower + "\n")
		writer.write(tabs(prevTabCount) + "var upper : Int = " + upper + "\n")
		writer.write(tabs(prevTabCount) + "var mimimum : Int = " + mimimum + "\n")
		writer.write(tabs(prevTabCount) + "var jitter : Int = " + jitter + "\n")
		writer.write(tabs(prevTabCount) + "var traceSet : SporadicConstraintGenerator = null" + "\n")
	}
	
	protected def generateGenerateTrace(writer: FileWriter, prevTabCount: Int, repetitionCount: Int, resultFilePath: String) : Unit = {
		writer.write(tabs(prevTabCount) + "def generateTrace(): Boolean = {" + "\n")
		writer.write(tabs(prevTabCount+1) + "tesslaMonitorInstance = new TesslaMonitor()" + "\n")
		writer.write(tabs(prevTabCount+1) + "traceSet = new SporadicConstraintGenerator()" + "\n")
		writer.write(tabs(prevTabCount+1) + "var res: Boolean = traceSet.generateTestTrace(eventCount, lower, upper, 1, jitter)" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (res) {" + "\n")
		writer.write(tabs(prevTabCount+2) + "traceSet.initOutput();" + "\n")
		writer.write(tabs(prevTabCount+1) + "}" + "\n")
		writer.write(tabs(prevTabCount+1) + "res" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
	
	protected def generateMeasureConstraintWriteEvents(writer: FileWriter, prevTabCount: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "for (i <- 0 to currentEvents.length-1){" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"event\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_event(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		//writer.write(tabs(prevTabCount+1) + "eventCounter = eventCounter+1" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
}