import java.io.FileWriter
import java.io.IOException

class TimeMeasureScalaClassCreatorTADLOrder extends TimeMeasureScalaClassCreator{

	def generateEntireObject(scalaFilePath: String, scalaObjectName: String, resultFilePath: String, repetitionCount: Int, eventCount: Int,
			maxDistSource: Int, maxDistSourceTarget: Int, printInputEvents: Boolean): Boolean= {
		var delayCreator = new TimeMeasureScalaClassCreatorTADLOrder
		try {
			var fileWriter = new FileWriter(scalaFilePath)
			fileWriter.write("//AUTOGENERATED FILE! CHANGES WILL BE OVERWRITTEN\n")
			fileWriter.write("import java.io._\n")
			fileWriter.write("object " + scalaObjectName + "{\n")
			fileWriter.write("\n")
			delayCreator.generateMainMethod(fileWriter, 1, repetitionCount, resultFilePath)
			fileWriter.write("\n")
			delayCreator.generateMemberVariableListGeneral(fileWriter, 1, eventCount)
			fileWriter.write("\n")
			delayCreator.generateMemberVariableListExtended(fileWriter, 1, maxDistSource, maxDistSourceTarget)
			fileWriter.write("\n")
			delayCreator.generateMeasureConstraint(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			delayCreator.generateMeasureMultiple(fileWriter, 1)
			fileWriter.write("\n")
			delayCreator.generateStoreResultsToFile(fileWriter, 1)
			fileWriter.write("\n")
			delayCreator.generateAverage(fileWriter, 1)
			fileWriter.write("\n")
			delayCreator.generateOutputFuncValue(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			delayCreator.generateOutputFuncFinal(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			delayCreator.generateGenerateTrace(fileWriter, 1, repetitionCount, resultFilePath)
			fileWriter.write("}\n")
			fileWriter.flush()
			fileWriter.close()
		} catch {
			case e: IOException => return false
		}
		return true
	}

	protected def generateMemberVariableListExtended(writer: FileWriter, prevTabCount: Int, maxDistSource: Int, maxDistSourceTarget: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "var maxDistSource: Int = " + maxDistSource + "\n")
		writer.write(tabs(prevTabCount) + "var maxDistSourceTarget: Int = " + maxDistSourceTarget + "\n")
		writer.write(tabs(prevTabCount) + "var traceSet : OrderConstraintGenerator = null" + "\n")
	}
	
	protected def generateGenerateTrace(writer: FileWriter, prevTabCount: Int, repetitionCount: Int, resultFilePath: String) : Unit = {
		writer.write(tabs(prevTabCount) + "def generateTrace(): Boolean = {" + "\n")
		writer.write(tabs(prevTabCount+1) + "tesslaMonitorInstance = new TesslaMonitor()" + "\n")
		writer.write(tabs(prevTabCount+1) + "traceSet = new OrderConstraintGenerator()" + "\n")
		writer.write(tabs(prevTabCount+1) + "var res: Boolean = traceSet.generateTestTrace(eventCount,  maxDistSource, maxDistSourceTarget)" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (res) {" + "\n")
		writer.write(tabs(prevTabCount+2) + "traceSet.initOutput();" + "\n")
		writer.write(tabs(prevTabCount+1) + "}" + "\n")
		writer.write(tabs(prevTabCount+1) + "res" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
	
	protected def generateMeasureConstraintWriteEvents(writer: FileWriter, prevTabCount: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "for (i <- 0 to currentEvents.length-1){" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"source\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_source(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"target\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_target(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		//writer.write(tabs(prevTabCount+1) + "eventCounter = eventCounter+1" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
	

}