import java.io.FileWriter
import java.io.IOException

class TimeMeasureScalaClassCreatorTADLExecutionTime extends TimeMeasureScalaClassCreator{

	def generateEntireObject(scalaFilePath: String, scalaObjectName: String, resultFilePath: String, repetitionCount: Int, eventCount: Int,
			lower: Int, upper: Int, minDistance: Int, maxDistance: Int, numPreemptions: Int, preemptLength: Int, printInputEvents: Boolean): Boolean= {
		var constraintCreator = new TimeMeasureScalaClassCreatorTADLExecutionTime
		try {
			var fileWriter = new FileWriter(scalaFilePath)
			fileWriter.write("//AUTOGENERATED FILE! CHANGES WILL BE OVERWRITTEN\n")
			fileWriter.write("import java.io._\n")
			fileWriter.write("object " + scalaObjectName + "{\n")
			fileWriter.write("\n")
			constraintCreator.generateMainMethod(fileWriter, 1, repetitionCount, resultFilePath)
			fileWriter.write("\n")
			constraintCreator.generateMemberVariableListGeneral(fileWriter, 1, eventCount)
			fileWriter.write("\n")
			constraintCreator.generateMemberVariableListExtended(fileWriter, 1, lower, upper, minDistance, maxDistance,
				numPreemptions, preemptLength)
			fileWriter.write("\n")
			constraintCreator.generateMeasureConstraint(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			constraintCreator.generateMeasureMultiple(fileWriter, 1)
			fileWriter.write("\n")
			constraintCreator.generateStoreResultsToFile(fileWriter, 1)
			fileWriter.write("\n")
			constraintCreator.generateAverage(fileWriter, 1)
			fileWriter.write("\n")
			constraintCreator.generateOutputFuncValue(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			constraintCreator.generateOutputFuncFinal(fileWriter, 1, printInputEvents)
			fileWriter.write("\n")
			constraintCreator.generateGenerateTrace(fileWriter, 1, repetitionCount, resultFilePath)
			fileWriter.write("}\n")
			fileWriter.flush()
			fileWriter.close()
		} catch {
			case e: IOException => return false
		}
		return true
	}

	protected def generateMemberVariableListExtended(writer: FileWriter, prevTabCount: Int, lower: Int, upper: Int,
			minDistance: Int, maxDistance: Int, numPreemptions: Int, preemptLength: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "var lower: Int = " + lower + "\n")
		writer.write(tabs(prevTabCount) + "var upper: Int = " + upper + "\n")
		writer.write(tabs(prevTabCount) + "var minDistance: Int = " + minDistance + "\n")
		writer.write(tabs(prevTabCount) + "var maxDistance: Int = " + maxDistance + "\n")
		writer.write(tabs(prevTabCount) + "var numPreemptions: Int = " + numPreemptions + "\n")
		writer.write(tabs(prevTabCount) + "var preemptLength: Int = " + preemptLength + "\n")
		writer.write(tabs(prevTabCount) + "var traceSet : ExecutionTimeConstraintGenerator = null" + "\n")
	}
	
	protected def generateGenerateTrace(writer: FileWriter, prevTabCount: Int, repetitionCount: Int, resultFilePath: String) : Unit = {
		writer.write(tabs(prevTabCount) + "def generateTrace(): Boolean = {" + "\n")
		writer.write(tabs(prevTabCount+1) + "tesslaMonitorInstance = new TesslaMonitor()" + "\n")
		writer.write(tabs(prevTabCount+1) + "traceSet = new ExecutionTimeConstraintGenerator()" + "\n")
		writer.write(tabs(prevTabCount+1) + "var res: Boolean = traceSet.generateTestTrace(eventCount, lower, upper, minDistance, maxDistance, numPreemptions, preemptLength)" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (res) {" + "\n")
		writer.write(tabs(prevTabCount+2) + "traceSet.initOutput();" + "\n")
		writer.write(tabs(prevTabCount+1) + "}" + "\n")
		writer.write(tabs(prevTabCount+1) + "res" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
	
	protected def generateMeasureConstraintWriteEvents(writer: FileWriter, prevTabCount: Int) : Unit = {
		writer.write(tabs(prevTabCount) + "for (i <- 0 to currentEvents.length-1){" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"start\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_start(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"stop\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_stop(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"preempt\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_preempt(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		writer.write(tabs(prevTabCount+1) + "if (currentEvents(i).getOwnerStream().getName().equals(\"resume\"))" + "\n")
		writer.write(tabs(prevTabCount+2) + "tesslaMonitorInstance.set_var_resume(currentEvents(i).getColor(), currentEvents(i).getTimeStamp())" + "\n")
		writer.write(tabs(prevTabCount+1) + "eventCounter = eventCounter+1" + "\n")
		writer.write(tabs(prevTabCount) + "}" + "\n")
	}
	

}